export const sounds = [
  { id: 0, label: '📯', sound: 'airhorn' },
  { id: 1, label: '🔪', sound: 'knife' },
  { id: 2, label: '🛎', sound: 'bell' },
  { id: 3, label: '❗', sound: 'exclamation' },
  { id: 4, label: '💿', sound: 'cd' },
  { id: 5, label: '🥁', sound: 'drum' },
  { id: 6, label: '💌', sound: 'emailReceive' },
  { id: 7, label: '📨', sound: 'inbox' },
  { id: 18, label: '🚕🚗', sound: 'musicJPCars' },
  { id: 19, label: '🧊🚢', sound: 'iceCube' },
  { id: 8, label: '🐮', sound: 'cow' },
  { id: 9, label: '🍄', sound: 'superMario' },
  { id: 10, label: '👏', sound: 'clap' },
  { id: 11, label: '🦠', sound: 'coronavirus' },
  { id: 12, label: 'IT IS WHAT IT IS', sound: 'itiswhatitis' },
  { id: 13, label: '4️⃣2️⃣0️⃣', sound: 'smokeWeedEveryday' },
  { id: 14, label: '🍑', sound: 'peach' },
  { id: 15, label: '🎷', sound: 'saxo' },
  { id: 16, label: '👋', sound: 'johncena' },
  { id: 17, label: '🐱', sound: 'miau' },
  { id: 20, label: '👨‍💼', sound: 'theoffice' },
  { id: 21, label: '😠', sound: 'no' },
  { id: 22, label: '🚗👱‍♀️', sound: 'itsBritneyBitch' },
  { id: 23, label: '🍪', sound: 'cookieCookie' },
  { id: 24, label: '😂', sound: 'risasenlatadas' }
];
